name: Report Repository Latest Version
description: Get the latest version/tag from a repository

inputs:
  git-repo-path:
    description: GitHub repository path (e.g., owner/repo)
    required: true
    default: 'vrossiciandt/reusable'

runs:
  using: "composite"
  steps:
    - id: setup-path
      name: setup-path
      shell: bash
      run: |
        echo "${{ github.action_path }}/scripts" | tee -a $GITHUB_PATH

    - name: Get Latest Version
      id: get-version
      shell: bash
      env:
        GIT_REPO_PATH: ${{ inputs.git-repo-path }}
      run: |
        get-latest-version "${GIT_REPO_PATH}"