name: 'Extract Values from Structured File'
description: 'Extract one or multiple values from structured files (YAML or JSON)'
inputs:
  file-path:
    description: 'Path to the file containing the data'
    required: true
  file-type:
    description: 'yaml or json'
    required: true
  attributes:
    description: 'JSON object with attribute names as keys and paths as values. Example: {"version": "version", "name": "metadata.name"}. For single value, use: {"value": "version"}'
    required: true
outputs:
  values:
    description: 'JSON object with all extracted values'
    value: ${{ steps.extract.outputs.values }}
  count:
    description: 'Number of values successfully extracted'
    value: ${{ steps.extract.outputs.count }}
  status:
    description: 'Status of extraction (success/failed)'
    value: ${{ steps.extract.outputs.status }}
runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.file-path }}" ] || [ -z "${{ inputs.attributes }}" ]; then
          echo "Error: file-path and attributes are required"
          exit 1
        fi
        
        if [ ! -f "${{ inputs.file-path }}" ]; then
          echo "Error: File not found at ${{ inputs.file-path }}"
          exit 1
        fi

    - name: Extract values
      id: extract
      shell: bash
      run: |
        FILE_PATH="${{ inputs.file-path }}"
        FILE_TYPE="${{ inputs.file-type }}"
        ATTRIBUTES='${{ inputs.attributes }}'
        
        echo "📄 Extracting from: $FILE_PATH"
        echo "📋 File type: $FILE_TYPE"
        
        # Inicializar objeto JSON resultado
        RESULT="{}"
        COUNT=0
        ERROR_COUNT=0
        
        # Iterar sobre cada atributo definido
        ATTRIBUTE_KEYS=$(echo "$ATTRIBUTES" | jq -r 'keys[]')
        
        while IFS= read -r key; do
          ATTRIBUTE_KEY=$(echo "$ATTRIBUTES" | jq -r ".\"$key\"")
          
          echo "  ├─ Extracting: $key (path: $ATTRIBUTE_KEY)"
          
          case "$FILE_TYPE" in
            yaml|yml)
              EXTRACTED=$(yq eval ".$ATTRIBUTE_KEY" "$FILE_PATH" 2>&1)
              ;;
            json)
              EXTRACTED=$(jq -r ".$ATTRIBUTE_KEY" "$FILE_PATH" 2>&1)
              ;;
            *)
              echo "    ❌ Unsupported file type: $FILE_TYPE"
              exit 1
              ;;
          esac
          
          if [ -z "$EXTRACTED" ] || [ "$EXTRACTED" = "null" ]; then
            echo "    ⚠️  Not found or empty"
            RESULT=$(echo "$RESULT" | jq --arg k "$key" '.[$k] = null')
            ERROR_COUNT=$((ERROR_COUNT + 1))
          else
            echo "    ✓ Found: $EXTRACTED"
            # IMPORTANTE: Sempre converter para string com --arg
            RESULT=$(echo "$RESULT" | jq --arg k "$key" --arg v "$EXTRACTED" '.[$k] = $v')
            COUNT=$((COUNT + 1))
          fi
        done <<< "$ATTRIBUTE_KEYS"
        
        echo ""
        echo "✓ Extraction complete"
        
        # Salvar resultado em temp para output
        echo "$RESULT" > /tmp/extraction_result.json
        
        # Ler e escapar para output de forma segura
        VALUES_JSON=$(cat /tmp/extraction_result.json)
        
        # Usar heredoc para evitar problemas com caracteres especiais
        {
          echo "values<<EXTRACTION_EOF"
          echo "$VALUES_JSON"
          echo "EXTRACTION_EOF"
          echo "count=$COUNT"
          echo "status=success"
        } >> $GITHUB_OUTPUT

    - name: Output summary
      shell: bash
      run: |
        echo "📊 Extraction Summary"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "File: ${{ inputs.file-path }}"
        echo "Type: ${{ inputs.file-type }}"
        echo "Values extracted: ${{ steps.extract.outputs.count }}"
        echo ""
        echo "Results:"
        echo "${{ steps.extract.outputs.values }}" | jq '.' 2>/dev/null || echo "${{ steps.extract.outputs.values }}"