name: Report Repository Latest Version
description: Get the latest version/tag from a repository

inputs:
  git-repo-path:
    description: GitHub repository path (e.g., owner/repo)
    required: false
    default: 'vrossiciandt/reusable'

runs:
  using: "composite"
  steps:
    - name: Get Latest Version
      id: get-version
      shell: bash
      env:
        GIT_REPO_PATH: ${{ inputs.git-repo-path }}
      run: |
        ${{ github.action_path }}/scripts/get-latest-version