name: composite-action
description: get the latest tag

runs:
  using: composite
  steps:
    - name: get the latest tag
      run: ${GITHUB_ACTION_PATH}/scripts/get-latest-version
      shell: bash
    
    - name: list files
      run: ls -l
      shell: bash