#! /bin/bash
set -e

echo "GET LATEST VERSION OF A REPOSITORY."
echo "---------------------"
echo "REPO....: ${GIT_REPO_PATH}"

echo "Retriving the lastest tag from ${GIT_REPO_PATH}..."

TAG=$(curl -s "https://api.github.com/repos/${GIT_REPO_PATH}/tags" | jq -r '.[0].name')

echo "The lastest tag is ${TAG}."